version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: demo-gin-test-db
    environment:
      POSTGRES_DB: demo_gin_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d demo_gin_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

volumes:
  test-postgres-data:
    driver: local

networks:
  test-network:
    driver: bridge